schedules = [
  { project_id: 6,
    period_id: 1,
    resource_id: 28,
    schedule_type_id: 1 },
  { project_id: 1,
    period_id: 2,
    resource_id: 6,
    schedule_type_id: 1 },
  { project_id: 1,
    period_id: 2,
    resource_id: 11,
    schedule_type_id: 1 },
  { project_id: 1,
    period_id: 2,
    resource_id: 13,
    schedule_type_id: 1 },
  { project_id: 1,
    period_id: 2,
    resource_id: 20,
    schedule_type_id: 1 },
  { project_id: 1,
    period_id: 2,
    resource_id: 22,
    schedule_type_id: 1 },
  { project_id: 1,
    period_id: 2,
    resource_id: 27,
    schedule_type_id: 1 },
  { project_id: 1,
    period_id: 2,
    resource_id: 14,
    schedule_type_id: 1 },
  { project_id: 1,
    period_id: 2,
    resource_id: 2,
    schedule_type_id: 1 },
  { project_id: 1,
    period_id: 3,
    resource_id: 12,
    schedule_type_id: 1 },
  { project_id: 1,
    period_id: 4,
    resource_id: 12,
    schedule_type_id: 1 },
  { project_id: 1,
    period_id: 2,
    resource_id: 16,
    schedule_type_id: 1 },
  { project_id: 1,
    period_id: 2,
    resource_id: 21,
    schedule_type_id: 1 },
  { project_id: 1,
    period_id: 5,
    resource_id: 30,
    schedule_type_id: 1 },
  { project_id: 2,
    period_id: 2,
    resource_id: 3,
    schedule_type_id: 1 },
  { project_id: 2,
    period_id: 2,
    resource_id: 9,
    schedule_type_id: 1 },
  { project_id: 2,
    period_id: 2,
    resource_id: 25,
    schedule_type_id: 1 },
  { project_id: 2,
    period_id: 2,
    resource_id: 29,
    schedule_type_id: 1 },
  { project_id: 2,
    period_id: 6,
    resource_id: 10,
    schedule_type_id: 1 },
  { project_id: 2,
    period_id: 1,
    resource_id: 17,
    schedule_type_id: 1 },
  { project_id: 2,
    period_id: 2,
    resource_id: 7,
    schedule_type_id: 1 },
  { project_id: 2,
    period_id: 2,
    resource_id: 8,
    schedule_type_id: 1 },
  { project_id: 2,
    period_id: 2,
    resource_id: 24,
    schedule_type_id: 1 },
  { project_id: 3,
    period_id: 2,
    resource_id: 1,
    schedule_type_id: 1 },
  { project_id: 3,
    period_id: 7,
    resource_id: 19,
    schedule_type_id: 1 },
  { project_id: 3,
    period_id: 8,
    resource_id: 30,
    schedule_type_id: 1 },
  { project_id: 3,
    period_id: 5,
    resource_id: 19,
    schedule_type_id: 1 },
  { project_id: 3,
    period_id: 2,
    resource_id: 26,
    schedule_type_id: 1 },
  { project_id: 3,
    period_id: 2,
    resource_id: 23,
    schedule_type_id: 1 },
  { project_id: 5,
    period_id: 9,
    resource_id: 4,
    schedule_type_id: 1 },
  { project_id: 7,
    period_id: 7,
    resource_id: 30,
    schedule_type_id: 1 },
  { project_id: 4, period_id: 3,
    resource_id: 18,
    schedule_type_id: 1 },
  { project_id: 4,
    period_id: 3,
    resource_id: 15,
    schedule_type_id: 1 }
]

schedules.each { |schedule_attrs| Schedule.find_or_create_by(schedule_attrs) }
