default: &default
  adapter: postgresql
  encoding: unicode
  host: db
  pool: 5
  user: postgres
  password: postgres

development:
  <<: *default
  database: team_workflow_development

test:
  <<: *default
  database: team_workflow_test

production:
  <<: *default
  database: team_workflow_production
