default: &default
  adapter: postgresql
  pool: 5
  timeout: 5000
  host: localhost

development:
  <<: *default
  database: team_workflow_development

test:
  <<: *default
  database: team_workflow_test

production:
  <<: *default
  database: team_workflow_production
